#!/usr/bin/env python3
"""
check_file_size_budget.py

File-size ratchet for an existing codebase.

Two tiers:
  * Files at or under the budget must stay at or under it.
  * Files already over the budget when the ratchet was introduced are
    grandfathered at their recorded size: they may shrink, never grow. When one
    shrinks, its ceiling is tightened so the space cannot be reclaimed later.

The baseline lives in .agents/file-size-baseline.json and is part of the repository.
New files are never grandfathered — a file created after the baseline must meet
the budget outright.

Modes:
  --init            seed the baseline from the current tree (run once)
  --staged          check staged files, tighten ceilings that improved (pre-commit)
  --changed         check files changed against HEAD, report only (agent hooks)
  --report [paths]  planning aid: show remaining headroom for the given paths
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

BUDGET = 400
BASELINE_PATH = ".agents/file-size-baseline.json"
CHECKED_SUFFIXES = ('.py',)
EXCLUDED_PREFIXES = ('vendor/', 'third_party/', 'node_modules/', 'build/', 'software/sdk/', 'tests/', 'test/')
# Matched anywhere in the path, for vendored trees nested inside the project.
EXCLUDED_FRAGMENTS = ()
VENDOR_COPYRIGHTS = (b'nxp', b'freescale', b'arm limited', b'st microelectronics', b'stmicroelectronics', b'texas instruments', b'microchip', b'silicon laboratories', b'nordic semiconductor', b'the qt company', b'cmsis')
ESTABLISHED_PATTERNS = []

_ROOT = subprocess.run(
    ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True
).stdout.strip()
if _ROOT:
    os.chdir(_ROOT)


GENERATED_MARKERS = (
    b"@generated", b"do not edit", b"do not modify", b"automatically generated",
    b"auto-generated", b"autogenerated", b"generated by",
)


# A marker alone cannot exempt a file. The exemption exists for vendored and
# machine-generated trees; if one comment were sufficient, an agent that has
# read the rule could opt out of the budget in a single line — and the rule
# text tells it exactly which line. So a marker only counts inside a location
# that is plausibly not ours.
GENERATED_LOCATION = re.compile(
    r"(^|/)(vendor|third_party|node_modules|generated|gen|__generated__|"
    r"externals?|deps|_deps|dist|build|proto|protos|sdk)(/|$)")


def looks_generated_or_vendored(path: str, staged: bool = False) -> bool:
    """Machine-generated and third-party files are not ours to decompose.

    Recognised by a third-party copyright (self-evidently not ours), or by a
    generator marker in a directory that is plausibly generated output.
    """
    head = read_bytes(path, staged)[:4000].lower()
    if not head:
        return False
    # A foreign copyright is sufficient on its own: we cannot refactor it.
    if any(vendor in head for vendor in VENDOR_COPYRIGHTS):
        return True
    if any(marker in head for marker in GENERATED_MARKERS):
        return bool(GENERATED_LOCATION.search(path))
    return False


def is_checked(path: str, extra_excludes=(), staged: bool = False) -> bool:
    if not path.endswith(CHECKED_SUFFIXES):
        return False
    if any(path.startswith(p) for p in EXCLUDED_PREFIXES):
        return False
    if any(f in path for f in EXCLUDED_FRAGMENTS):
        return False
    if any(fragment and fragment in path for fragment in extra_excludes):
        return False
    return not looks_generated_or_vendored(path, staged)


def count_lines(path: str, staged: bool = False):
    """Count lines in the content that is actually being judged.

    Under --staged that is the INDEX copy, not the working tree. Selecting
    paths from the index while measuring the working tree lets an oversized
    file through and records a ceiling the commit never met.
    """
    if staged:
        result = subprocess.run(["git", "show", ":{}".format(path)],
                                capture_output=True)
        if result.returncode == 0:
            return result.stdout.count(b"\n") + (
                0 if result.stdout.endswith(b"\n") or not result.stdout else 1)
        return None
    try:
        with open(path, "rb") as handle:
            return sum(1 for _ in handle)
    except OSError:
        return None


def read_bytes(path: str, staged: bool = False):
    if staged:
        result = subprocess.run(["git", "show", ":{}".format(path)],
                                capture_output=True)
        return result.stdout if result.returncode == 0 else b""
    try:
        with open(path, "rb") as handle:
            return handle.read(4000)
    except OSError:
        return b""


def load_baseline() -> dict:
    try:
        with open(BASELINE_PATH, encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, json.JSONDecodeError):
        return {"budget": BUDGET, "policy": "ratchet", "files": {}}


def save_baseline(baseline: dict) -> None:
    with open(BASELINE_PATH, "w", encoding="utf-8") as handle:
        json.dump(baseline, handle, indent=2, sort_keys=True)
        handle.write("\n")


def git_files(*args: str):
    res = subprocess.run(["git", *args], capture_output=True, text=True)
    if res.returncode != 0:
        return []
    return [f for f in res.stdout.splitlines() if f.strip()]


def decomposition_guidance(path: str) -> str:
    pattern_hint = ""
    if ESTABLISHED_PATTERNS:
        names = ", ".join("*" + p for p in ESTABLISHED_PATTERNS)
        pattern_hint = (
            "\n     5. Follow this repository's own vocabulary — it already uses "
            + names + ".\n        Put the extracted unit where those live and register it the same way."
        )
    return (
        "\n  HOW TO FIX THIS (read before editing):\n"
        "  Do NOT satisfy this check by deleting blank lines, collapsing formatting,\n"
        "  inlining variables, shortening names, or moving code into comments. Those\n"
        "  reduce the line count without reducing complexity, and will be rejected in\n"
        "  review. Reduce the file by moving responsibility out of it.\n\n"
        "  Work through these in order:\n"
        "     1. Single Responsibility — list the distinct reasons this file has to\n"
        "        change. Each separate reason is a separate module.\n"
        "     2. Open/Closed — find the conditional or switch that grows every time a\n"
        "        case is added, and replace it with polymorphism (Strategy) or a\n"
        "        registry/Factory, so new cases are added without editing this file.\n"
        "     3. DRY — extract logic repeated here or duplicated elsewhere.\n"
        "     4. Dependency direction — separate I/O, parsing, and configuration from\n"
        "        the core logic so each part is independently testable."
        + pattern_hint
        + "\n\n  If the extraction genuinely does not belong to the current ticket, state\n"
        "  that explicitly in the pull request description. Do not bypass this check\n"
        "  silently."
    )


def check(paths, baseline, tighten: bool):
    grandfathered = baseline.get("files", {})
    budget = baseline.get("budget", BUDGET)
    extra = tuple(baseline.get("exclude", []))
    failures, tightened = [], {}

    for path in paths:
        # Under --staged the file may legitimately be absent from the working
        # tree (staged deletion is handled by the prune below).
        if not Path(path).is_file() or not is_checked(path, extra, tighten):
            continue
        lines = count_lines(path, tighten)
        if lines is None:
            continue
        ceiling = grandfathered.get(path)

        if ceiling is None:
            if lines > budget:
                failures.append(
                    "FILE SIZE BUDGET EXCEEDED: {}\n"
                    "  current: {} lines | budget: {} lines | over by: {}\n"
                    "  This file is not grandfathered, so it must meet the budget.".format(
                        path, lines, budget, lines - budget)
                    + decomposition_guidance(path))
        elif lines > ceiling:
            failures.append(
                "GRANDFATHERED FILE GREW: {}\n"
                "  current: {} lines | ceiling: {} lines | budget: {} lines\n"
                "  This file was already over budget when the ratchet was introduced,\n"
                "  so it may shrink but never grow. This change adds {} line(s).\n"
                "  Put the new code in a new, properly sized module, or bring this file\n"
                "  below its ceiling as part of the same change.".format(
                    path, lines, ceiling, budget, lines - ceiling)
                + decomposition_guidance(path))
        elif lines < ceiling:
            tightened[path] = lines

    # Only tighten when the run is otherwise clean. Recording a tighter ceiling
    # for a commit that is about to be rejected would strand the baseline ahead
    # of the tree: if the author then reverts the shrink, the file would be
    # measured against a ceiling it never actually reached.
    if failures:
        tighten = False

    # Drop entries for files that no longer exist. Leaving them behind is a
    # bypass, not a courtesy: deleting a grandfathered path and recreating it
    # would otherwise let a brand-new oversized file inherit the old ceiling.
    removed = [p for p in grandfathered if not Path(p).is_file()]
    if removed and tighten:
        for path in removed:
            grandfathered.pop(path, None)
        baseline["files"] = grandfathered
        save_baseline(baseline)
        subprocess.run(["git", "add", BASELINE_PATH], check=False)
        print("File-size ratchet: dropped {} deleted file(s) from the baseline:"
              .format(len(removed)))
        for path in sorted(removed):
            print("  {}".format(path))

    if tightened and tighten:
        for path, lines in tightened.items():
            if lines <= budget:
                grandfathered.pop(path, None)
            else:
                grandfathered[path] = lines
        baseline["files"] = grandfathered
        save_baseline(baseline)
        subprocess.run(["git", "add", BASELINE_PATH], check=False)
        print("File-size ratchet tightened (this improvement is now the new ceiling):")
        for path, lines in sorted(tightened.items()):
            print("  {} -> {} lines{}".format(
                path, lines, " (now within budget, no longer grandfathered)"
                if lines <= budget else ""))
    elif tightened and not failures:
        print("File-size ratchet: {} file(s) shrank. Run with --staged to record "
              "the tighter ceilings.".format(len(tightened)))

    return failures


def do_init():
    existing = load_baseline()
    extra = tuple(existing.get("exclude", []))
    tracked = git_files("ls-files")
    files = {}
    for path in tracked:
        if not Path(path).is_file() or not is_checked(path, extra):
            continue
        lines = count_lines(path)
        if lines is not None and lines > BUDGET:
            files[path] = lines
    baseline = {
        "budget": BUDGET,
        "policy": "ratchet",
        "comment": ("Files recorded here were already over budget when the ratchet "
                    "was introduced. They may shrink, never grow. Entries are removed "
                    "automatically once a file falls within budget. Do not add entries "
                    "by hand to excuse a new violation."),
        "exclude": list(extra),
        "exclude_comment": ("Path fragments excluded from the budget entirely — use "
                            "for vendored or generated trees this project does not "
                            "own. After editing, re-run with --init to reseed."),
        "files": files,
    }
    save_baseline(baseline)
    print("Seeded {} with {} grandfathered file(s) over {} lines.".format(
        BASELINE_PATH, len(files), BUDGET))
    if files:
        worst = sorted(files.items(), key=lambda kv: -kv[1])[:5]
        print("Largest:")
        for path, lines in worst:
            print("  {} lines  {}".format(lines, path))
    if len(files) > 50:
        tops = {}
        for path in files:
            top = path.split("/")[0] if "/" in path else "."
            tops[top] = tops.get(top, 0) + 1
        ranked = sorted(tops.items(), key=lambda kv: -kv[1])[:5]
        print("")
        print("WARNING: {} files were grandfathered. That is high enough to suggest "
              "vendored or".format(len(files)))
        print("generated code is being counted as this project's own. Contributors by "
              "top-level directory:")
        for top, count in ranked:
            print("  {}: {} file(s)".format(top, count))
        print("Review the entries; add path fragments to the \"exclude\" list in "
              "{} and re-run".format(BASELINE_PATH))
        print("with --init to reseed. A baseline full of third-party code makes the "
              "ratchet meaningless.")


def do_report(paths):
    baseline = load_baseline()
    grandfathered = baseline.get("files", {})
    budget = baseline.get("budget", BUDGET)
    extra = tuple(baseline.get("exclude", []))
    if not paths:
        paths = [p for p in git_files("ls-files") if is_checked(p, extra)]
    print("File-size headroom (budget {} lines):".format(budget))
    for path in paths:
        if not Path(path).is_file():
            print("  {}: new file — must be written within {} lines".format(path, budget))
            continue
        lines = count_lines(path)
        if lines is None:
            continue
        ceiling = grandfathered.get(path, budget)
        state = "grandfathered" if path in grandfathered else "budget"
        headroom = ceiling - lines
        verdict = ("{} line(s) of headroom".format(headroom) if headroom > 0
                   else "AT CEILING — any addition must be offset by an extraction")
        print("  {}: {} lines / {} {} — {}".format(
            path, lines, ceiling, state, verdict))
    print("\nPlan extractions before writing code: if the work does not fit the "
          "headroom above,\ndecide now which responsibility moves out and where it "
          "goes.")


def main():
    args = sys.argv[1:]
    if "--init" in args:
        do_init()
        return
    if "--report" in args:
        do_report([a for a in args if not a.startswith("--")])
        return

    baseline = load_baseline()
    if "--changed" in args:
        paths = git_files("diff", "--name-only", "HEAD")
        tighten = False
    else:
        paths = git_files("diff", "--cached", "--name-only")
        tighten = True
    explicit = [a for a in args if not a.startswith("--")]
    if explicit:
        paths, tighten = explicit, False

    failures = check(paths, baseline, tighten)
    if failures:
        print("=" * 78)
        for failure in failures:
            print(failure)
            print("-" * 78)
        print("=" * 78)
        sys.exit(1)


if __name__ == "__main__":
    main()
