#!/usr/bin/env bash
<<<<<<< HEAD
# Auto-generated by ultimaker-agentic-bootstrap from detected repo tooling.
# Runs the repository's own linters/formatters on files changed since HEAD.
set -uo pipefail

# Antigravity invokes hooks with cwd set to the hooks.json directory —
# always operate from the repository root.
cd "$(git rev-parse --show-toplevel)" || exit 0

FAIL=0
CHANGED=$(git diff --name-only HEAD 2>/dev/null | head -100)
if [ -z "$CHANGED" ]; then
    exit 0
fi

py_files=$(echo "$CHANGED" | grep -E '\.py$' || true)
if [ -n "$py_files" ] && command -v flake8 >/dev/null 2>&1; then
    echo "$py_files" | xargs flake8 || FAIL=1
fi

if [ -f .agents/hooks/check_file_size_budget.py ]; then
    python3 .agents/hooks/check_file_size_budget.py --changed || FAIL=1
fi

if [ -f .agents/hooks/check_complexity.py ]; then
    python3 .agents/hooks/check_complexity.py --changed || true
fi

if [ -f .agents/hooks/suggest-skills.py ]; then
    python3 .agents/hooks/suggest-skills.py || true
fi

exit $FAIL
=======
set -e

# Run quick format/linter checks if available
if command -v flake8 >/dev/null 2>&1; then
  git diff --name-only --cached | grep -E '\.py$' | xargs -r flake8 --select=E9,F63,F7,F82 || true
fi
>>>>>>> origin/UC-3697_platform_emulation_and_seeding
