name: Build package on Push or Pull Request

on:
  push
  
jobs:
  Prepare:
    name: 'Prepare'
    uses: Ultimaker/embedded-workflows/.github/workflows/prepare_env.yml@main
    with:
      BUILD_DOCKER_CACHE: true
    secrets: inherit

  Build:
    name: 'Build'
    needs: Prepare
    uses: Ultimaker/embedded-workflows/.github/workflows/build.yml@main
    with:
      RELEASE_VERSION: ${{ needs.Prepare.outputs.RELEASE_VERSION }}
    secrets: inherit

  Release_Package:
    name: 'Release'
    needs: [Prepare, Build]
    if: ${{ (success() && needs.Prepare.outputs.RELEASE_REPO != 'none') ||
            (failure() && needs.Build.result == 'success' && needs.Prepare.outputs.RELEASE_REPO == 'packages-dev') }}
    uses: Ultimaker/embedded-workflows/.github/workflows/release_pkg.yml@main
    with:
      RELEASE_REPO: ${{ needs.Prepare.outputs.RELEASE_REPO }}
    secrets: inherit
